package de.deadlocker8.budgetmaster.databasemigrator.destination.repeating.modifier;

import de.deadlocker8.budgetmaster.databasemigrator.destination.DestinationRepository;

public interface DestinationRepeatingModifierYearsRepository extends DestinationRepository<DestinationRepeatingModifierYears>
{
}
