package de.deadlocker8.budgetmaster.databasemigrator.destination.repeating.modifier;

import de.deadlocker8.budgetmaster.databasemigrator.destination.DestinationRepository;

public interface DestinationRepeatingModifierMonthsRepository extends DestinationRepository<DestinationRepeatingModifierMonths>
{
}
