package de.deadlocker8.budgetmaster.databasemigrator.destination.repeating.end;

import de.deadlocker8.budgetmaster.databasemigrator.destination.DestinationIntegerRepository;

public interface DestinationRepeatingEndAfterXTimesIntegerRepository extends DestinationIntegerRepository<DestinationRepeatingEndAfterXTimes, Integer>
{
}
